accounts/urls.py
from django.urls import path, include
from . import views


app_name = "accounts"

urlpatterns = [
    path("register/",views.register, name="register"),
    path("login/", views.login_user, name="login_user"),
    path("logout/", views.logout_user, name="logout_user"),
    path("profile/", views.profile, name="profile"),
]

main/urls.py
from django.urls import path, include
from . import views


app_name = 'main'

urlpatterns = [
        path("", views.home, name="home"),
        path("ditail/<int:id>/",views.ditail, name="ditail"),
        path("addmovies", views.add_movie, name="add_movie"),
        path("edit/<int:id>", views.edit_movies, name="edit_movies"),
        path("delete/<int:id>", views.delete_movie, name="delete_movie"),
        path("addreview/<int:id>", views.add_review, name="add_review"),
        path("editreview/<int:movie_id>/<int:review_id>", views.edit_review, name="edit_review"),
        path("deletereview/<int:movie_id>/<int:review_id>", views.delete_review, name="delete_review"),

]

movieReview/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('main.urls')),
    path("accounts/",include('accounts.urls'))
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Movie(models.Model):
    #Movie table + type of fields 
    name = models.CharField(max_length = 300)
    director = models.CharField(max_length = 300)
    cast = models.CharField(max_length = 800)
    description = models.TextField(max_length = 5000)
    relised_date = models.DateField()
    averidgerating = models.FloatField(default=0)
    image = models.URLField(default=None,null=True)
    
    def __str__(self):
        return self.name
        
    def __unicode__(self):
        return self.name
        
class Review(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete = models.CASCADE)
    comment = models.TextField(max_length= 1000)
    raiting = models.FloatField(default=0)
    
    def __str__(self):
        return self.user.username

main/forms.py
from django import forms
from .models import *


#movie add form
class MovieForm(forms.ModelForm):

    class Meta:
        model = Movie
        fields = ('name','director','cast','description','relised_date','image')
        
class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ('comment','raiting')
        

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from .forms import *
from django.db.models import Avg

# Create your views here.


def home(request):
    query = request.GET.get("title")
    allmovies = None
    if query:
        allmovies = Movie.objects.filter("title=query")
    else:
        allmovies = Movie.objects.all()#selct * from movie table
    context = {
    'movies':allmovies
    }
    
    return render(request, 'main/index.html',context)
    
 #ditail view   
def ditail(request,id):
    movie = Movie.objects.get(id=id)# Select everything(*) from the database with this id=id
    review = Review.objects.filter(movie=id).order_by("-comment")
    
    score = review.aggregate(Avg("raiting"))['raiting__avg']
    if score == None:
        score = 0
    context = { 'movie': movie,'reviews':review, 'averidge':score }
    return render(request, 'main/ditail.html',context)
    
#Add movies to database
def add_movie(request):
    if request.user.is_authenticated:
        if request.user.is_superuser:
        
    
            if request.method == "POST":
                form = MovieForm(request.POST or None) 
                
                
               #check if form is valid or not 
                if form.is_valid():
                    data = form.save(commit=False)
                    data.save()
                    return redirect('main:home')
            else:
                form = MovieForm()
            return render(request, 'main/addmovies.html', {'form':form,
                                                            'controller':"Add movies"})
        #if they are not admin
        else:
            return redirect('main:home')
            
    #if they are n login 
    return redirect('accounts:login_user')

#Edit movie
def edit_movies(request,id):
        if request.user.is_authenticated:
            if request.user.is_superuser:
                    #get the movie with the id
                movie = Movie.objects.get(id=id)
                    
                    #form check
                if request.method == "POST":
                    form = MovieForm(request.POST or None,instance=movie)
                        #check if form is valid
                    if form.is_valid():
                        data = form.save(commit=False)
                        data.save()
                        return redirect('main:ditail', id)
                        
                else:
                    form = MovieForm(instance=movie)
                return render(request, 'main/addmovies.html',{'form':form, 'controller':"Edit Movies"})
                #if they are not admin
            else:
                return redirect('main:home')
                
        #if they are n login 
        return redirect('accounts:login_user')
        
        
 #delete movie post    
def delete_movie(request,id):
    if request.user.is_authenticated:
        if request.user.is_superuser:


            movie = Movie.objects.get(id=id)
                
                #delete the movie -object
            movie.delete()
            return redirect('main:home')
    
    
    
            #if they are not admin
        else:
            return redirect('main:home')
            
    #if they are n login 
    return redirect('accounts:login_user')
    
  #addig review to a movie  
def add_review(request,id):
    if request.user.is_authenticated:
        movie = Movie.objects.get(id=id)
        
        if request.method == "POST":
            form = ReviewForm(request.POST or None)
            if form.is_valid():
                data = form.save(commit=False)
                data.comment = request.POST['comment']
                data.raiting = request.POST['raiting']
                data.user = request.user
                data.movie = movie
                data.save()
                return redirect('main:ditail', id)
 
        else:
            form = ReviewForm()
        return render(request, 'main/ditail.html',{'form':form})
        
    else:
        return redirect('accounts:login_user')
     
     #eding a review of a movie   
def edit_review(request,movie_id,review_id):
    if request.user.is_authenticated:
        movie = Movie.objects.get(id=movie_id)
        #review is after the movie 
        review = Review.objects.get(movie=movie, id=review_id)
        
        #check if the review is done by the looged in user
        if request.user == review.user:
            # grand permission to edit reiew 
            if request.method == "POST":
                form = ReviewForm(request.POST, instance=review)
                if form.is_valid():
                    data = form.save(commit=False)
                    if (data.raiting > 10) or (data.raiting < 0):
                        error = "Out of range.Please select raiting from 0 to 10"
                        return render(request, 'main/editreview.html',{'error':error, 'form':form})
                        
                    else: 
                        data.save()
                        return redirect('main:ditail', movie_id)
                    
            else:
                form = ReviewForm(instance=review)
            return render(request, 'main/editreview.html',{'form':form})
            # if user is not the autor of the review
        else:
            return redirect('main:ditail', movie_id)
         #if user not logged in   
    else:
        return redirect('main:login')
        
        
#delit review
def delete_review(request,movie_id,review_id):
    if request.user.is_authenticated:
        movie = Movie.objects.get(id=movie_id)
        #review is after the movie 
        review = Review.objects.get(movie=movie, id=review_id)
        
        #check if the review is done by the looged in user
        if request.user == review.user:
            # grand permissin delete
            review.delete()
        
        return redirect('main:ditail', movie_id)
         #if user not logged in   
    else:
        return redirect('main:login')
    

        
    

main/templates/main/addmovies.html
{% extends 'main/base.html'  %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">
	<div class="card">
		<div class=" card-body">
			<h3 class="text-center">{{ controller  }}</h3>
			<form action=""method="POST">
			{% csrf_token %}
			{{ form | crispy }}
			<input type="submit" value="{{ controller }}" class="btn btn-danger" ></input>
			
			</form>
		</div >
	</div>
</div>




{% endblock %}

main/templates/main/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	{% load static %}
	<link rel="stylesheet" href="{% static 'css/main.css' %}"></link>

    <title>Movie view</title>

  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'main:home' %}">Movie Review</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'main:home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'main:add_movie' %}">Add Movies</a>
      </li>
	  {% if user.is_authenticated %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{ user.username }}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'accounts:profile' %}">My profile</a>
          
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'accounts:logout_user' %}">logout</a>
        </div>
      </li>
	  {% else %}
	  <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:login_user' %}">Login</a>
      </li>
	  <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
      </li>
		
	  
	  
	  {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
	{% if user.is_authenticated %}
    <h1><center style="color:white;">Welcome!   {{ user.username }}</center></h1>
	{% endif %}
	{% block content %}
	{% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

main/templates/main/ditail.html
{% extends 'main/base.html' %}

{% block content %}

<div class="conteiner">
	<div class="card">
		<div class="card-body">
			<div class="row">
				<div class="col md-4">
				<img class="img fluid" src="{{movie.image}}" alt="{{movie.image}}">
				</div>
					
				<div class="col md-8">
				<h3 >{{ movie.name }}</h3>
				<h5 >{{ movie.description }}</h5>
				
				<p>Director: {{ movie.director }}</p>		
				<p>Cast: {{ movie.cast }}</p>
				<p>Raiting: {{ averidge }}/10</p>
				{% if user.is_superuser %}
				<a href="{% url 'main:edit_movies' movie.id %}" class="btn btn-warning" >Edit Movie</a>
				<a href="{% url 'main:delete_movie' movie.id %}" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this movie?');">Delete Movie</a>
				{% endif %}
				</div>
			</div>
		</div>
	</div>
	<br>
	<div class="card">
		<div class="card-body">
		<h3 class="text-center">Post Your Reviews</h3>
		<form action="{% url 'main:add_review' movie.id %}" method="POST">
		{% csrf_token %}
		<label for="comment">Review</label>
		<textarea name="comment" cols="8" rows="5" id="command" class="form-control"  ></textarea>
		
		<label for="raiting">Raiting (between 0 and 10):</label>
		<input type="range" id="raiting" step="0.5" name="raiting" min="0" max="10.0">
		
		<br>
		<input type="submit" class="btn btn-danger" value="Add review">
					
		</form>
		</div>
	</div>
	<br>
	<h2 class="text-center" style="color:white;">Reviews</h2>
	<div class="card" style="background-color:#908c8c">
		<div class="card-body">
		{% for review in reviews %}
			<div class="card" >
				<div class="card-body">
				<div class="row">
					<div class="col md-3">
						<h5 class="text-left">{{ review.user.username }}<h5>
						<h5>{{ review.raiting }}</h5>
						{% if request.user == review.user %}
						<a href="{% url 'main:edit_review' movie.id review.id %}" >Edit</a>
						<br>
						<a href="{% url 'main:delete_review' movie.id review.id %}" onclick="return confirm('Are you sure you want to delete this review?');" " >Delete</a>
						{% endif %}
					</div>
					<div class="col md-9">
						<p>{{ review.comment }}</p>
					</div>
				</div>
				</div>
			</div>
				<br>
		{% endfor %}
		
		</div>
	</div>
</div>


{% if request.user.is_authenticated %}
{% if request.user.is_superuser %}

<h1> {{ movie.name }}</h1>
<p>{{ movie.description }}</p>
<p>{{ movie.relised_date }}</p>
<p>{{ movie.averidgerating }}</p>
{% endif %}
{% endif %}

{% endblock %}

main/templates/main/editreview.html
{% extends 'main/base.html'  %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">
	<div class="card">
		<div class=" card-body">
			<h3 class="text-center">Edit Review</h3>
			<form action=""method="POST">
			{% csrf_token %}
			{{ form | crispy }}
			{% if error %}
			<h2 class="text-center">{{error}}</h2>
			
			{% endif %}
			<input type="submit" value="Save changes" class="btn btn-danger" ></input>
			
			</form>
		</div >
	</div>
</div>




{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block content %}

<div class="container">
	<div class="card" id="back" style="background-color:#94a2a2;">
		<div class="card-body">
			<div class="row ">
				{% for movie in movies %}
					<div class="col md-4">
						<div class="card text-center">
							<div class="card-body">
								<img src="{{movie.image}}" alt="Movie poster" class="img fluid" style="width:55%;">
								<h3 class="card-center">{{movie.name}}</h3>
								<p>{{ movie.relised_date }}</p>
								<p>{{ movie.description }}</p>
								<a href="{% url 'main:ditail' movie.id %}">Read more....</a>
							</div>
					</div>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>
</div>
{% endblock %}